[package]
name = "godata"
version = "0.1.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "godata"
crate-type = ["rlib", "cdylib"]


[dependencies]
directories = "5.0.1"
nanoid = "0.4.0"
pyo3 = "0.19.2"
rusqlite = { version = "0.29.0", features = ["bundled"] }
serde = "1.0.188"
serde_json = "1.0.106"
serde_rusqlite = "0.33.1"
